language: node_js
os: linux
node_js: 8
cache: yarn
before_script:
- yarn lint
script:
- yarn build
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi
- yarn test
